name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Altere para master se a sua branch principal for master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1. Cria uma pasta temporária para juntar tudo o que o site precisa
      - name: Criar pasta de build
        run: mkdir public_dist

      # 2. Copia todo o conteúdo de frontend para essa pasta temporária
      - name: Copiar arquivos do frontend
        run: cp -r frontend/* public_dist/

      # 3. Move os arquivos HTML para a raiz do site e renomeia home.html para index.html
      - name: Ajustar paginas e links
        run: |
          cp -r public_dist/html/* public_dist/
          mv public_dist/home.html public_dist/index.html
          rm -rf public_dist/html

      # 4. Configura e envia a pasta completa para o GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'public_dist/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
