name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Altere para master se a sua branch principal for master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/uses/checkout@v4

      # Cria um arquivo index.html na raiz do frontend que apenas redireciona para html/home.html
      - name: Criar redirecionamento index.html
        run: |
          echo '<meta http-equiv="refresh" content="0; URL='\''html/home.html'\''">' > frontend/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v4

      # Envia a pasta frontend inteira para o GitHub
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'frontend/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
